AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: MyEMRCluster
      ReleaseLabel: emr-7.0.0
      Applications:
        - Name: Spark
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1  
          InstanceType: m5.xlarge
          Name: MASTER
        CoreInstanceGroup: 
          InstanceCount: 2
          InstanceType: m5.xlarge
          Name: CORE
        Ec2SubnetId: "subnet-024446bcf36b23364"  # Define the subnet for instances
        Ec2KeyName: "Ashishkey"
      JobFlowRole: "EMR_EC2_DefaultRole"
      ServiceRole: "EMR_DefaultRole"
          
  MySparkStep:
    Type: AWS::EMR::Step
    Properties:
      Name: MySparkStep
      ActionOnFailure: CONTINUE
      HadoopJarStep:
        Jar: command-runner.jar
        Args:
          - spark-submit
          - --deploy-mode
          - cluster
          - --class
          - org.apache.spark.deploy.Mysparkob
          - s3://finalproject1-a/a.py
          - --jars
          - s3://finalproject1-a/spark-sql-kafka-0-10_2.12-3.2.1.jar
          - s3://finalproject1-a/kafka-clients-2.1.1.jar
      JobFlowId: !Ref MyEMRCluster
      ServiceRole: "EMR_DefaultRole"  # Specify a service role for the step

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: prj-workflow

  MyEMRTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Ref MyEMRCluster
      Description: Triggers the EMR job
      Name: MyEMRTrigger
      Type: ON_DEMAND
      WorkflowName: prj-workflow

  MyEMRTrigger1:
    Type: AWS::Glue::Trigger
    DependsOn:
      - MySparkStep
    Properties:
      Actions:
        - JobName: !Ref MySparkStep
      Description: Triggers the Spark job
      Name: MyEMRTrigger1
      Type: ON_DEMAND
      Role: arn:aws:iam::963746058908:role/LabRole
      WorkflowName: prj-workflow
